import { Router } from 'express';
import authRoutes from './auth.routes';
import assetRoutes from './asset.routes';
import employeeRoutes from './employee.routes';
import departmentRoutes from './department.routes';
import locationRoutes from './location.routes';
import maintenanceRoutes from './maintenance.routes';
import dashboardRoutes from './dashboard.routes';
import reportRoutes from './report.routes';
import auditRoutes from './audit.routes';
import notificationRoutes from './notification.routes';
import userRoutes from './user.routes';
import settingRoutes from './setting.routes';
import healthRoutes from './health.routes';
import importRoutes from './import.routes';
import assignmentRoutes from './assignment.routes';
import transferRoutes from './transfer.routes';
import returnRoutes from './return.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/assets', assetRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/transfers', transferRoutes);
router.use('/returns', returnRoutes);
router.use('/employees', employeeRoutes);
router.use('/departments', departmentRoutes);
router.use('/locations', locationRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/notifications', notificationRoutes);
router.use('/users', userRoutes);
router.use('/settings', settingRoutes);
router.use('/import', importRoutes);

export default router;
